### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Alexey-T** [myCrack/cuda_hilite_occurrences#3]
добавил в install.inf, в секцию начала

    homepage=https://github.com/myCrack/cuda_hilite_occurrences

**Comment by myCrack** [comment]
То что в репозитории -- могут все править.

**Comment by Alexey-T** [comment]
я прошу эту правку. чтобы потом она у меня осталась. когда сделаю pull.

**Comment by myCrack** [comment]
Сделал.
