### ISSUE TITLE
проблема, завис при выделении нуля

### ISSUE THREAD

**Issue by Alexey-T** [myCrack/cuda_hilite_occurrences#6]
двоичный файл. necros-vision.mod
[necros-vision.zip](https://github.com/myCrack/cuda_hilite_occurrences/files/211469/necros-vision.zip)

в строке 10 (от 1) выделяю нулевые байты где-то от кол. 4-6.
Куд завис при выделении

если задать SEL_ALLOW             = False, все ОК

**Comment by myCrack** [comment]
В строках 9, 10, 11 выделял от начала строки символы от 1 до 15, и не зависает.

При выделении одного символа - зависает на секунд 3-4, потом подсвечивает найденное, чем больше символов выделяю, тем на меньше зависает.

Так-что я не знаю в чем проблема, у меня версия редактора 1.3.5.3

**Comment by Alexey-T** [comment]
зависает на секунд 10.

**Comment by myCrack** [comment]
В чем проблема? нужно ускорить поиск или подсветку?

**Comment by Alexey-T** [comment]
нужно прервать поиск если поиск длится больше Н секунд (Н=2).

**Comment by myCrack** [comment]
Потом сделаю.
У меня уже есть некоторые правки, чтобы можно было делать переопределения для разных лексеров, еще чтобы настройки были в отдельном файле а не в коде, и чтобы цвета  автоматически подбирались в зависимости от темы. И не хочется сейчас и это делать.


Кстати, вот что заметил - выделяю один нулевой символ, после проходит секунд 5, потом в строке состояния пишется `Matches hilited: 87601`, и только потом подсвечивается то что нашлось. А должно -- красится текст и только потом пишется в строке состояния.

И вот у меня вопрос -- как так? получается что метод `Editor.attr()` возвращает управление до того как покрасит текст?

**Comment by Alexey-T** [comment]
он не красит. Он делает запись в массиве.След. покраска учтет записи (после работы плага)

**Comment by myCrack** [comment]
Нужно иметь возможность из питона управлять этим массивом.

Ведь если заранее указать размер массива, то можно уже потом его наполнять, и тем самым избежать лишнего выделения\перераспределения памяти, но подозреваю что там не все так просто. Только из-за маршалинга уже невозможно напрямую менять этот массив, а еще ведь в питоне динамическая типизация, т.е. в массив можем напихать разных типов (и неизбежно выделение новой памяти)... Но как бы там нибыло, можно хотя-бы размер указывать из питона...


Но если еще подумать -- сколько плагинов используют эту фичу?.. spell check и hilite all occurrences (и то, как я понимаю spell checker заранее не знает сколько неправильных слов есть), может еще пару плагинов, т.е. делать что-то в этом направлении сомнительно. Так как почти никому не нужно.

**Comment by Alexey-T** [comment]
- можно хотя-бы размер указывать из питона...
нет. не надо. Паскаль аллоцирует по 100 элементов (это не массив а список. TList) потом по 200, потом по 400 и тд
